version: '3.8'
services:
  mariadb:
    image: 'mariadb:10.5'
    restart: unless-stopped
    container_name: test-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password_erp
      MYSQL_DATABASE: quasar_erp_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - test-network

  backend:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./src:/usr/src/app/src
      - ./db:/usr/src/app/db
      - ./package.json:/usr/src/app/package.json
      - /usr/src/app/node_modules
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  db_data: {}
